---
- name: Provision VPC
  ec2_vpc_net:
    name: "{{namespace}}-vpc"
    cidr_block: "{{ vpc_cidr }}"
    tags:
      Name: "{{namespace}}-vpc"
      namespace: "{{namespace}}"
    region: "{{ region }}"
    state: "{{ state }}"
  register: vpc_facts

- name: Provision internet gateway
  ec2_vpc_igw:
    vpc_id: "{{vpc_facts['vpc']['id']}}"
    region: "{{ region }}"
    state: "{{ state }}"
  register: igw_facts

- name: Provision subnet
  ec2_vpc_subnet:
    vpc_id: "{{vpc_facts['vpc']['id']}}"
    cidr: "{{subnet_cidr}}"
    tags:
      Name: "{{namespace}}-subnet"
      namespace: "{{namespace}}"
    region: "{{ region }}"
    state: "{{ state }}"
  register: subnet_facts

- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{vpc_facts['vpc']['id']}}"
    tags:
      Name: "{{namespace}}-route"
      namespace: "{{namespace}}"
    subnets:
      - "{{subnet_facts['subnet']['id']}}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{igw_facts['gateway_id']}}"
    region: "{{ region }}"
    state: "{{ state }}"
  register: route_facts

- name: register vpc facts
  set_fact:
   vpc_id: "{{vpc_facts['vpc']['id']}}"

- name: set availability zone fact
  set_fact:
    availability_zone: "{{subnet_facts['subnet']['availability_zone']}}"