region: "sa-east-1"
public_dns_zone: "rg.osecloud.com"
public_subdomain_prefix: "apps"
aws_key_pair: "gupta2"
ami_id: "ami-5fd69a33"
provision_ssl_certs: false

install_metrics: false
install_prometheus: false
install_logging: false
install_gluster: false

gluster_ami_size: t2.large
gluster_volume_size: 100

users:
  - {name: admin, password: Welcome1, admin: true}
create_generic_user: true
generic_user_prefix: user
generic_user_count: 51
generic_user_password: openshift

bastion_ami_size: t2.large
master_ami_size: t2.large
node_ami_size: t2.large

master_root_volume_size: 100
node_root_volume_size: 100
docker_volume_size: 10

app_nodes: 1
deployment_type: "openshift-enterprise"
ocp_version: "3.7"

namespace: "openshift"
dns_zone: "ose.local"
vpc_cidr: "10.0.0.0/16"
subnet_cidr: "10.0.1.0/24"
amazon_user: "ec2-user"
htpasswd_path: "/etc/origin/master/htpasswd"


cf_account_email: '9chakri@gmail.com'
cf_account_api_token: ''
le_certsdir: '~/'
domain: 'ck.osecloud.com'
csr_subj: '/C=NO/ST=Oslo/L=Oslo/O=National Inquisitor/OU=McKraken/CN={{ domain }}'
ansible_python_interpreter: /usr/bin/python2.7
